export const users = [
    {"id":7,"name":"Rev","nickName":"Gordy","address":"5481 Merchant Circle","courseAndYear":"anon","avatar":"https://robohash.org/deseruntdoloremolestiae.png?size=50x50&set=set1"},
    {"id":4,"name":"Ms","nickName":"Ammamaria","address":"7413 Rowland Drive","courseAndYear":"Course2","avatar":"https://robohash.org/quiahictempore.png?size=50x50&set=set1"},
    {"id":8,"name":"Honorable","nickName":"Rhys","address":"1 Kim Place","courseAndYear":"anon","avatar":"https://robohash.org/providentquasiut.png?size=50x50&set=set1"},
    {"id":0,"name":"Ms","nickName":"Devlin","address":"32 Daystar Junction","courseAndYear":"anon","avatar":"https://robohash.org/veletvero.png?size=50x50&set=set1"},
    {"id":10,"name":"Ms","nickName":"Anette","address":"12 Anzinger Drive","courseAndYear":"anon","avatar":"https://robohash.org/odioexplicaboaut.png?size=50x50&set=set1"},
    {"id":3,"name":"Mrs","nickName":"Andriette","address":"0764 Heffernan Way","courseAndYear":"Course3","avatar":"https://robohash.org/nesciuntexut.png?size=50x50&set=set1"},
    {"id":1,"name":"Honorable","nickName":"Bruis","address":"7601 Emmet Avenue","courseAndYear":"Course3","avatar":"https://robohash.org/nullaculpaasperiores.png?size=50x50&set=set1"},
    {"id":6,"name":"Mr","nickName":"Korney","address":"4 Gerald Hill","courseAndYear":"Course1","avatar":"https://robohash.org/sitetdolorem.png?size=50x50&set=set1"},
    {"id":10,"name":"Honorable","nickName":"Ingram","address":"3 Rockefeller Alley","courseAndYear":"Course1","avatar":"https://robohash.org/velitsedlaborum.png?size=50x50&set=set1"},
    {"id":6,"name":"Honorable","nickName":"Pamela","address":"08 Dottie Hill","courseAndYear":"Course1","avatar":"https://robohash.org/rerumestdolore.png?size=50x50&set=set1"},
    {"id":3,"name":"Honorable","nickName":"Marcile","address":"29299 Thompson Way","courseAndYear":"Course2","avatar":"https://robohash.org/molestiasestut.png?size=50x50&set=set1"},
    {"id":5,"name":"Mrs","nickName":"Susana","address":"78758 Mitchell Terrace","courseAndYear":"anon","avatar":"https://robohash.org/assumendalaudantiumquaerat.png?size=50x50&set=set1"},
    {"id":2,"name":"Honorable","nickName":"Lacy","address":"95915 Esker Parkway","courseAndYear":"Course2","avatar":"https://robohash.org/etculpadeleniti.png?size=50x50&set=set1"},
    {"id":1,"name":"Rev","nickName":"Juditha","address":"77 School Street","courseAndYear":"anon","avatar":"https://robohash.org/excepturicorporistotam.png?size=50x50&set=set1"},
    {"id":3,"name":"Dr","nickName":"Barby","address":"2 Sunnyside Place","courseAndYear":"Course2","avatar":"https://robohash.org/repudiandaeundedistinctio.png?size=50x50&set=set1"},
    {"id":0,"name":"Mr","nickName":"Vivian","address":"3452 Maple Court","courseAndYear":"anon","avatar":"https://robohash.org/temporautquia.png?size=50x50&set=set1"},
    {"id":3,"name":"Honorable","nickName":"Marcelline","address":"02 Morningstar Plaza","courseAndYear":"Course1","avatar":"https://robohash.org/quiexblanditiis.png?size=50x50&set=set1"},
    {"id":0,"name":"Honorable","nickName":"Nerissa","address":"82 Lakewood Center","courseAndYear":"Course1","avatar":"https://robohash.org/rerumdistinctionemo.png?size=50x50&set=set1"},
    {"id":7,"name":"Mrs","nickName":"Townsend","address":"798 Canary Point","courseAndYear":"anon","avatar":"https://robohash.org/utsedmaxime.png?size=50x50&set=set1"},
    {"id":0,"name":"Mr","nickName":"Pablo","address":"94214 New Castle Pass","courseAndYear":"Course2","avatar":"https://robohash.org/illumvoluptatumfugiat.png?size=50x50&set=set1"},
    {"id":3,"name":"Ms","nickName":"Hana","address":"407 Surrey Plaza","courseAndYear":"Course2","avatar":"https://robohash.org/quinihilid.png?size=50x50&set=set1"},
    {"id":1,"name":"Dr","nickName":"Becca","address":"1107 Linden Place","courseAndYear":"Course3","avatar":"https://robohash.org/nostrumquiasunt.png?size=50x50&set=set1"},
    {"id":7,"name":"Ms","nickName":"Riccardo","address":"56430 Saint Paul Trail","courseAndYear":"Course1","avatar":"https://robohash.org/natussapienteut.png?size=50x50&set=set1"},
    {"id":0,"name":"Ms","nickName":"Robin","address":"8 Heath Crossing","courseAndYear":"Course3","avatar":"https://robohash.org/voluptatemetmaxime.png?size=50x50&set=set1"},
    {"id":10,"name":"Mr","nickName":"Gerhardine","address":"3 Nobel Terrace","courseAndYear":"Course3","avatar":"https://robohash.org/excepturiutquas.png?size=50x50&set=set1"},
];
export default users;